#!/usr/bin/with-contenv bash

set -eu
set -o pipefail


s6-svwait /var/run/s6/services/libvirtd


virsh net-define /vmrc/nat.xml
virsh net-start "$NAT_NAME"
virsh net-dumpxml "$NAT_NAME"


printf '\n' >&69
sleep infinity

