#!/usr/bin/env bash

set -eu
set -o pipefail

s6-svwait /var/run/s6/services/libvirtd

virsh net-define /vmrc/br0.xml
virsh net-autostart br0
virsh net-start br0
virsh net-dumpxml br0


echo >&69
sleep infinity

