#!/usr/bin/with-contenv bash

set -eu
set -o pipefail

s6-svwait /var/run/s6/services/libvirtd

virsh net-define /vmrc/br0.xml
virsh net-autostart "$VIRTBR_NAME"
virsh net-start "$VIRTBR_NAME"
virsh net-dumpxml "$VIRTBR_NAME"


echo >&69
sleep infinity

