#!/usr/bin/with-contenv bash

set -eu
set -o pipefail


VM_IP="$(< /vmrc/ip_addr)"
VM_NET="$(< /vmrc/network)"


if [[ "$1" == "$VM_NAME" ]]
then
  if [[ "$2" = "stopped" ]] || [[ "$2" = "reconnect" ]]
  then
    route-nat --bridge "$NAT_NAME" --ip "$VM_IP" --network "$VM_NET" --state off
  fi

  if [[ "$2" = "start" ]] || [[ "$2" = "reconnect" ]]
  then
    route-nat --bridge "$NAT_NAME" --ip "$VM_IP" --network "$VM_NET" --state on
  fi
fi

