#!/usr/bin/with-contenv bash

set -eu
set -o pipefail


VMDK="/config"
DOMAIN_XML="$VMDK/$VM_NAME.xml"


sleep infinity
# if [[ -f "$DOMAIN_XML" ]]
# then
#   virsh define "$DOMAIN_XML"
#   while true
#   do
#     virsh start "$VM_NAME" || true
#     sleep 3
#   done
# else
#   hr
#   >&2 echo WARNING -- VM Not Found
#   >&2 echo Build VM using 'CMD :: new'
#   hr
#   sleep infinity
# fi

