#!/usr/bin/with-contenv bash

set -eu
set -o pipefail


s6-svwait /var/run/s6/services/nat-init
s6-svwait /var/run/s6/services/macvtap-init


VMDK="/config"
DOMAIN_XML="$VMDK/$VM_NAME.xml"


if [[ -f "$DOMAIN_XML" ]]
then
  virsh define "$DOMAIN_XML"
  while true
  do
    virsh start "$VM_NAME" 2>&1 > /dev/null || true
    sleep 3
  done
else
  >&2 printf '%s\n' 'WARNING -- VM Not Found'
  >&2 printf '%s\n' 'Build VM using -- CMD new'
  >&2 printf '%s\n' 'See https://github.com/ms-jpq/windows-in-docker'
  sleep infinity
fi

