#!/usr/bin/with-contenv bash

set -eu
set -o pipefail


s6-svwait /var/run/s6/services/libvirtd


if [[ -n "$LAN_IF" ]]
then
  virsh net-define /vmrc/lan.xml
  virsh net-start "$LAN_NAME"
  virsh net-dumpxml "$LAN_NAME"
fi


printf '\n' >&420
sleep infinity

