#!/usr/bin/with-contenv bash

set -eu
set -o pipefail


s6-svwait /var/run/s6/services/libvirtd


if [[ -n "$MACVTAP_IF" ]]
then
  # virsh iface-bridge "$MACVTAP_IF" "$MACVTAP_NAME"
  echo 555

  # virsh net-define /vmrc/macvtap.xml
  # virsh net-start "$MACVTAP_NAME"
  # virsh net-dumpxml "$MACVTAP_NAME"
fi


printf '\n' >&420
sleep infinity

