#!/usr/bin/env bash

set -eu
set -o pipefail

cd /vmrc || exit 1

s6-svwait /var/run/s6/services/libvirtd

virsh net-define /vmrc/macvtap0.xml
virsh net-start macvtap0
virsh net-dumpxml macvtap0

echo >&69

sleep infinity
