#!/usr/bin/with-contenv bash

set -eu
set -o pipefail


s6-svwait -U /var/run/s6/services/nat-init


VMDK="/config"
DOMAIN_XML="$VMDK/$VM_NAME.xml"


check_running() {
  local dead=($(virsh list --name --state-shutoff))
  for vm in "${dead[@]}"
  do
    if [[ "$vm" == "$VM_NAME" ]]
    then
      exit
    fi
  done
}


if [[ -f "$DOMAIN_XML" ]]
then
  printf '\n%s\n' '--------------------------------------------------------'
  cat "$DOMAIN_XML"
  printf '\n%s\n' '--------------------------------------------------------'

  virsh define "$DOMAIN_XML"
  virsh start "$VM_NAME"

  while true
  do
    check_running
    sleep 1
  done
else
  >&2 printf '%s\n' '--------------------------------------------------------'
  >&2 printf '%s\n' 'WARNING -- VM Not Found'
  >&2 printf '%s\n' 'Build VM using -- CMD new'
  >&2 printf '%s\n' 'See https://github.com/ms-jpq/windows-in-docker'
  >&2 printf '%s\n' '--------------------------------------------------------'
  sleep infinity
fi

