#!/usr/bin/with-contenv bash

set -eu
set -o pipefail


s6-svwait /var/run/s6/services/lxd


bridges="$(brctl show | tail -n +2 | cut -f 1)"
exists=0
while read -r bridge
do
  if [[ "$bridge" == "$LXDBR_NAME" ]]
  then
    exists=1
  fi
done <<< "$bridges"


if [[ "$exists" -eq 0 ]]
then
  lxd init --preseed < /vmrc/lxd-init.yml
  touch /vmrc/lxd-init-done

  echo '-----------------------------------------------'
  echo 'LXD INIT'
  echo '-----------------------------------------------'
else
  echo '-----------------------------------------------'
  echo 'NO INIT'
  echo '-----------------------------------------------'
fi


echo >&420
sleep infinity

