#!/usr/bin/with-contenv bash

set -eu
set -o pipefail


s6-svwait /var/run/s6/services/libvirtd


virsh net-define /vmrc/network.xml
virsh net-autostart "$MACVTAP_NAME"
virsh net-start "$MACVTAP_NAME"
virsh net-dumpxml "$MACVTAP_NAME"


printf '\n' >&69
sleep infinity

