#!/usr/bin/with-contenv bash

set -eu
set -o pipefail


s6-svwait /var/run/s6/services/libvirtd


virsh net-define /vmrc/network.xml
virsh net-start "$VIRTBR_INTERNAL"
virsh net-dumpxml "$VIRTBR_INTERNAL"


printf '\n' >&69
sleep infinity

